### DISCUSSION TITLE
Customize match highlighting/underlining

### DISCUSSION THREAD

**Discussion by onomou** [nothingislost/obsidian-dynamic-highlights#82] [Q&A]
How do I customize how matches are highlighted? Right now, when I select a word, the matches are underlined with a purple dash.
![image](https://github.com/user-attachments/assets/5beba07d-b2f8-40aa-b605-b37850351d27)

Actually, it appears that the selected word itself is underlined with a purple dash.
![image](https://github.com/user-attachments/assets/c60d38a0-faeb-4343-974b-eb574adf4624)

I would like to replicate how VS Code highlights matches by changing the background of the text. Example:
![image](https://github.com/user-attachments/assets/8ef13df5-1762-4003-b763-2a3a17973e9f)

**Comment by darshanagopal** [comment]
You'll need to modify the editor's settings or configuration files. Customise highlights under Settings

**Comment by onomou** [comment]
Thank you for the hint. But I have not been able to find highlights under Settings. Can you give more detail?

**Reply by darshanagopal** [reply]
This is a guide to VS Syntax Highlight Guide. There is changes to be made in configuration file.
https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

**Reply by onomou** [reply]
I read that document and do not see how it helps. This question is about how to get Dynamic Highlights to highlight other matches. However, I managed to solve this problem by finding the style in the source and making my own:

https://github.com/nothingislost/obsidian-dynamic-highlights/blob/2b13ff5924de822e9dcb514352ed0170aa06e0dd/styles.css#L3-L11

```css
/* If cursor is in a word, this is used */
.cm-matched-word {
    /* background-color: #4d4f51; */
}

/* If word is selected, this is used */
.cm-matched-string {
    background-color: #4d4f51;
}
```

I matched the CSS classes by using the inspector `Ctrl + Shift + i` and watching what happened as the cursor entered a word or the word was highlighted.
