### ISSUE TITLE
FR: Make save button bigger

### ISSUE THREAD

**Issue by brimwats** [nothingislost/obsidian-dynamic-highlights#64]
Sometimes it's really hard to hit the "save button" if you move the mouse across the regex button. An example:
![Obsidian_DxEmzxa6j9](https://user-images.githubusercontent.com/73113656/177395000-5c56b9fb-c1be-45b6-819c-94e06a776ffa.gif)

Not sure if this is just a theme issue—I can file a bug request at Minimal if it is. I remember it being an issue on Primary too tho

**Comment by hiocean** [comment]
same problem found!!

**Comment by dsmeltz** [comment]
Maybe even move the Save button to below the Custom CSS text box?  That way it will never be overrun by the Regex toggle.

**Comment by Moyf** [comment]
Actually you can add this css snippet to fix it:
```css
.highlighter-settings-regex input[type="checkbox"] {
    width: 30px !important;
    height: 20px !important;
}
```

Add from here:
![image](https://github.com/nothingislost/obsidian-dynamic-highlights/assets/4013062/19247c3b-7c40-4599-9742-885265a7b048)

And then the button zone is normal:
![image](https://github.com/nothingislost/obsidian-dynamic-highlights/assets/4013062/bc2dff6a-24ee-4d7d-aba2-4b8ce24c945a)
